service {
    name = "onboarding-service"
    port = 8020
    port = ${?SERVICE_PORT}
}

database {
    url = "jdbc:postgresql://localhost:5432/rappiclone_onboarding"
    url = ${?DATABASE_URL}
    user = "rappiclone"
    user = ${?DATABASE_USER}
    password = "rappiclone_dev"
    password = ${?DATABASE_PASSWORD}
    maxPoolSize = 10
}
