service {
    name = "catalog-service"
    port = 8004
    port = ${?SERVICE_PORT}
}

database {
    url = "jdbc:postgresql://localhost:5432/rappiclone_catalog"
    url = ${?DATABASE_URL}
    user = "rappiclone"
    user = ${?DATABASE_USER}
    password = "rappiclone_dev"
    password = ${?DATABASE_PASSWORD}
    maxPoolSize = 10
}

kafka {
    bootstrapServers = "localhost:9094"
    bootstrapServers = ${?KAFKA_BOOTSTRAP_SERVERS}
    groupId = "catalog-service"
}
