service {
    name = "tenant-service"
    port = 8001
    port = ${?SERVICE_PORT}
}

database {
    url = "jdbc:postgresql://localhost:5432/rappiclone_tenant"
    url = ${?DATABASE_URL}
    user = "rappiclone"
    user = ${?DATABASE_USER}
    password = "rappiclone_dev"
    password = ${?DATABASE_PASSWORD}
    maxPoolSize = 10
}

redis {
    url = "redis://localhost:6379"
    url = ${?REDIS_URL}
}

kafka {
    bootstrapServers = "localhost:9094"
    bootstrapServers = ${?KAFKA_BOOTSTRAP_SERVERS}
    groupId = "tenant-service"
}
