service {
    name = "geolocation-service"
    port = 8015
    port = ${?SERVICE_PORT}
}

nominatim {
    baseUrl = "http://localhost:8088"
    baseUrl = ${?NOMINATIM_BASE_URL}
}

osrm {
    baseUrl = "http://localhost:5000"
    baseUrl = ${?OSRM_BASE_URL}
}

redis {
    url = "redis://localhost:6379"
    url = ${?REDIS_URL}
}
